name: Build and Push App

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Select which package to deploy'
        required: true
        type: choice
        options:
          - subscriber
          - admin
        default: subscriber
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - main
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/commit.yaml'
env:
    IMAGE_TAG: ${{ github.sha }}

jobs:

  update-main:
    name: Update main test
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.environment == 'production' ||
      github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Update image tag values
        run: |
          echo "Updating Helm values with new image tag: ${{ env.IMAGE_TAG }}" >> update.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add update.txt
          git commit -m "chore: Update txt values with new image tag: ${{ env.IMAGE_TAG }}"
          git push origin main

