
name:  update Pipeline

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image tag'
        required: true
        default: ''
        type: string
      env:
        description: 'Environment'
        required: true
        default: 'sandbox'
        type: string

jobs:
  pre-work:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout
        uses: actions/checkout@v3
        

      - uses: 1arp/create-a-file-action@0.2
        if: ${{ github.event.inputs.env }} != 'production'
        with:
          path: "./"
          file: 'django_settings.tftpl'
          content: django_settings

      - uses: 1arp/create-a-file-action@0.2
        if: ${{ github.event.inputs.env }} == 'production'
        with:
          path: "./"
          file: 'django_settings.tftpl'
          content: django_settings_production
