
name:  update Pipeline

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image tag'
        required: true
        default: ''
        type: string
      env:
        description: 'Environment'
        required: true
        default: 'sandbox'
        type: string

jobs:
  pre-work:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout
        uses: actions/checkout@v3
        

      - name: not prod
        if: ${{ ${{ github.event.inputs.env }} != 'production' }}
        run: echo "not production"

      - name: prod
        if: ${{ ${{ github.event.inputs.env }} == 'production' }}
        run: echo "production"
