name: Pipeline

on:
  push:
    branches:
      - 'main'

jobs:

  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Add Jira Ticket number env property
        run: |
          echo "JIRA_TICKET=`echo ${GITHUB_REF##*/}| cut -c1-7`" >> $GITHUB_ENV
          echo ${JIRA_TICKET}
        
